import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import deved from '../public/dev-ed-wave.png'
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"

export default function Home() {
  return (
    <div >
      <Head>
        <title>Viveks Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-10 lg:px-40'>
        <section className=' min-h-screen'>
          <nav className=' py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>
              Vivek
            </h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className=' cursor-pointer text-2xl'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded ml-8' href='#'>Resume</a></li>
            </ul>
          </nav>
          <div className=' text-center p-10 '>
            <h2 className=' text-5xl py-2 text-teal-600 font-medium'>Vivek Tarun</h2>
            <h3 className=' text-2xl py-2'>Software Developer</h3>
            <p className='text-mid py-5 leading-8 text-gray-800'>nterview Kickstart is the gold standard in tech interview prep. It is the only technical interview prep platform that hosts 17 technical domain courses. Our programs include a comprehensive curriculum, unmatched teaching methods, guidance of 300+ FAANG+ instructors & SMEs, and career coaching to help you nail your next tech interview.</p>
          </div>
          <div className=' text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className=' relative mx-auto bg-gradient-to-b overflow-hidden from-teal-600 rounded-full w-80 h-80'>
            <Image alt='image' src={deved} layout="fill" objectFit='cover' />
          </div>
        </section>
        {/* First part is done  */}
        <section> 
          <div>
            <h3 className='text-3xl py-1'>
              Services I offer
            </h3>
            <p className='text-mid py-5 leading-8 text-gray-800'>
            Kickstart is the <span className='text-teal-500'>how to do</span> gold standard in tech interview prep. It is the only technical interview prep platform that hosts 17 technical domain courses. Our programs include a comprehensive curriculum,
            </p>
            <p className='text-mid py-5 leading-8 text-gray-800'>
              interview prep platform that hosts 17 technical domain courses. Our programs include a comprehensive 
            </p>
          </div>
          <div>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10'>
              <Image alt='image' src={design} width= {100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful design</h3>
              <p className='py-2'>
                Creating elegant design suited for your name desing theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tool i use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10'>
              <Image alt='image' src={code} width= {100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful design</h3>
              <p className='py-2'>
                Creating elegant design suited for your name desing theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tool i use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10'>
              <Image alt='image' src={consulting} width= {100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful design</h3>
              <p className='py-2'>
                Creating elegant design suited for your name desing theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tool i use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>
              Portofolio 
            </h3>
            <p className='text-mid py-5 leading-8 text-gray-800'>
            Kickstart is the <span className='text-teal-500'>how to do</span> gold standard in tech interview prep. It is the only technical interview prep platform that hosts 17 technical domain courses. Our programs include a comprehensive curriculum,
            </p>
            <p className='text-mid py-5 leading-8 text-gray-800'>
              interview prep platform that hosts 17 technical domain courses. Our programs include a comprehensive 
            </p>
          </div>
          <div>
            <div>
              <Image alt='image' src={web1}/>
            </div>
            <div>
              <Image alt= 'alt' src={web2}/>
            </div>
            <div>
              <Image alt= 'alt' src={web3}/>
            </div>
            <div>
              <Image  alt= 'alt'src={web4}/>
            </div>
            <div>
              <Image alt= 'alt' src={web5}/>
            </div>
            <div>
              <Image alt= 'alt' src={web6}/>
            </div>
          </div>
        </section>
      </main>
      
    </div>
  )
}
